# VarianceThreshold

In [2]:
from sklearn.feature_selection import VarianceThreshold
import numpy as np
import pandas as pd


In [20]:
rng = np.random.RandomState(0)
data = np.c_[
    rng.rand(100).reshape(-1, 1),
    rng.randn(100).reshape(-1, 1)
]

In [21]:
data[:5, :]

array([[ 0.5488135 , -1.16514984],
       [ 0.71518937,  0.90082649],
       [ 0.60276338,  0.46566244],
       [ 0.54488318, -1.53624369],
       [ 0.4236548 ,  1.48825219]])

In [24]:
np.var(data, axis=0)

array([ 0.08311782,  0.99276922])

In [27]:
vt = VarianceThreshold(threshold=0.8 *(1 - 0.8))

In [28]:
vt.fit_transform(data_uni)

ValueError: No feature in X meets the variance threshold 0.16000

In [40]:
from sklearn.feature_selection import VarianceThreshold
X = np.array([
    [0, 0, 1],
    [0, 1, 0],
    [1, 0, 0],
    [0, 1, 1],
    [0, 1, 0],
    [0, 1, 1]])
sel = VarianceThreshold(threshold=(.8 * (1 - .8)))
X, sel

(array([[0, 0, 1],
        [0, 1, 0],
        [1, 0, 0],
        [0, 1, 1],
        [0, 1, 0],
        [0, 1, 1]]), VarianceThreshold(threshold=0.15999999999999998))

In [42]:
sel.fit_transform(X)


array([[0, 1],
       [1, 0],
       [0, 0],
       [1, 1],
       [1, 0],
       [1, 1]])

In [47]:
X.var(axis=0), sel.variances_

(array([ 0.13888889,  0.22222222,  0.25      ]),
 array([ 0.13888889,  0.22222222,  0.25      ]))

In [45]:
sel.variances_ > sel.threshold

array([False,  True,  True], dtype=bool)