In [2]:
""" This simple code is desinged to teach a basic user to read in the files in python, simply find what proportion of males and females survived and make a predictive model based on this
Author : AstroDave
Date : 18 September 2012
Revised: 28 March 2014

"""

' This simple code is desinged to teach a basic user to read in the files in python, simply find what proportion of males and females survived and make a predictive model based on this\nAuthor : AstroDave\nDate : 18 September 2012\nRevised: 28 March 2014\n\n'

In [3]:
import csv as csv
import numpy as np


In [10]:
# Load in the csv file
csv_file_object = csv.reader(open('train.csv', 'r')) 
# Skip the fist line as it is a header
header = next(csv_file_object)
# Create a variable to hold the data
data = []

# Skip through each row in the csv file,
for row in csv_file_object:
    # adding each row to the data variable
    data.append(row[0:])
# Then convert from a list to an array.
data = np.array(data)

header, data

(['PassengerId',
  'Survived',
  'Pclass',
  'Name',
  'Sex',
  'Age',
  'SibSp',
  'Parch',
  'Ticket',
  'Fare',
  'Cabin',
  'Embarked'],
 array([['1', '0', '3', ..., '7.25', '', 'S'],
        ['2', '1', '1', ..., '71.2833', 'C85', 'C'],
        ['3', '1', '3', ..., '7.925', '', 'S'],
        ..., 
        ['889', '0', '3', ..., '23.45', '', 'S'],
        ['890', '1', '1', ..., '30', 'C148', 'C'],
        ['891', '0', '3', ..., '7.75', '', 'Q']], 
       dtype='<U82'))

In [11]:
# Now I have an array of 12 columns and 891 rows
# I can access any element I want, so the entire first column would
# be data[0::,0].astype(np.float) -- This means all of the rows (from start to end), in column 0
# I have to add the .astype() command, because
# when appending the rows, python thought it was a string - so needed to convert

# Set some variables
number_passengers = np.size(data[0::,1].astype(np.float))
number_survived = np.sum(data[0::,1].astype(np.float))
proportion_survivors = number_survived / number_passengers

In [12]:
number_passengers

891

In [13]:
number_survived

342.0

In [14]:
proportion_survivors

0.38383838383838381

In [17]:
# I can now find the stats of all the women on board,
# by making an array that lists True/False whether each row is female
women_only_stats = data[0::,4] == "female" 	# This finds where all the women are
men_only_stats = data[0::,4] != "female" 	# This finds where all the men are (note != means 'not equal')


In [20]:
women_only_stats[:5]

array([False,  True,  True,  True, False], dtype=bool)

In [21]:
men_only_stats[:5]

array([ True, False, False, False,  True], dtype=bool)

In [23]:
# I can now filter the whole data, to find statistics for just women, by just placing
# women_only_stats as a "mask" on my full data -- Use it in place of the '0::' part of the array index. 
# You can test it by placing it there, and requesting column index [4], and the output should all read 'female'
# e.g. try typing this:   data[women_only_stats,4]
women_onboard = data[women_only_stats,1].astype(np.float)
men_onboard = data[men_only_stats,1].astype(np.float)


In [25]:
women_onboard[:5]

array([ 1.,  1.,  1.,  1.,  1.])

In [26]:
men_onboard[:5]

array([ 0.,  0.,  0.,  0.,  0.])

In [28]:
# and derive some statistics about them
proportion_women_survived = np.sum(women_onboard) / np.size(women_onboard)
proportion_men_survived = np.sum(men_onboard) / np.size(men_onboard)

print('Proportion of women who survived is %s' % proportion_women_survived)
print('Proportion of men who survived is %s' % proportion_men_survived)


Proportion of women who survived is 0.742038216561
Proportion of men who survived is 0.188908145581


In [29]:
# Now that I have my indicator that women were much more likely to survive,
# I am done with the training set.
# Now I will read in the test file and write out my simplistic prediction:
# if female, then model that she survived (1) 
# if male, then model that he did not survive (0)

# First, read in test.csv
test_file = open('test.csv', 'r')
test_file_object = csv.reader(test_file)
header = next(test_file_object)
header

['PassengerId',
 'Pclass',
 'Name',
 'Sex',
 'Age',
 'SibSp',
 'Parch',
 'Ticket',
 'Fare',
 'Cabin',
 'Embarked']

In [31]:
# Also open the a new file so I can write to it. Call it something descriptive
# Finally, loop through each row in the train file, and look in column index [3] (which is 'Sex')
# Write out the PassengerId, and my prediction.

predictions_file = open("gendermodel.csv", "w")
predictions_file_object = csv.writer(predictions_file)
predictions_file_object.writerow(["PassengerId", "Survived"])	# write the column headers
# For each row in test file,
for row in test_file_object:
    if row[3] == 'female':
        # is it a female, if yes then
        # write the PassengerId, and predict 1
        predictions_file_object.writerow([row[0], "1"])
    else:
        # or else if male,
        # write the PassengerId, and predict 0.
        predictions_file_object.writerow([row[0], "0"])

# Close out the files.
test_file.close()
predictions_file.close()
