# numpy.linspace

In [1]:
import numpy as np

## 個数指定

In [2]:
np.linspace(1, 5, num=5)

array([ 1.,  2.,  3.,  4.,  5.])

## 末尾を含めない
- optionでの指定
- optionなしでの実現

In [3]:
np.linspace(1, 5, num=5, endpoint=False)

array([ 1. ,  1.8,  2.6,  3.4,  4.2])

In [4]:
np.linspace(1, 5, num=6)[:5]

array([ 1. ,  1.8,  2.6,  3.4,  4.2])

## 間隔と一緒にタプルで返す

In [5]:
np.linspace(1, 5, num=5, retstep=True)

(array([ 1.,  2.,  3.,  4.,  5.]), 1.0)

In [6]:
np.linspace(1, 5, num=5, endpoint=False, retstep=True)

(array([ 1. ,  1.8,  2.6,  3.4,  4.2]), 0.8)